package com.saigangili.shortener.service;

import com.saigangili.shortener.model.ShortUrl;
import com.saigangili.shortener.repository.ShortUrlRepository;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import org.springframework.dao.DataIntegrityViolationException;

import java.util.Optional;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.ArgumentMatchers.anyString;
import static org.mockito.Mockito.*;

@ExtendWith(MockitoExtension.class)
class ShortUrlServiceTest {

    @Mock
    private ShortUrlRepository shortUrlRepository;

    private ShortUrlService shortUrlService;

    @BeforeEach
    void setUp() {
        shortUrlService = new ShortUrlService(shortUrlRepository);
    }

    @Test
    void createShortUrl_withCustomAlias_savesAndReturnsShortUrl() {
        when(shortUrlRepository.existsByShortCode("my-alias")).thenReturn(false);
        when(shortUrlRepository.save(any(ShortUrl.class))).thenAnswer(inv -> inv.getArgument(0));

        ShortUrl result = shortUrlService.createShortUrl("https://example.com", "my-alias", "user1");

        assertEquals("my-alias", result.getShortCode());
        assertEquals("https://example.com", result.getTargetUrl());
        assertTrue(result.isCustom());
        assertEquals("user1", result.getCreatedBy());
        verify(shortUrlRepository).save(any(ShortUrl.class));
    }

    @Test
    void createShortUrl_withoutAlias_generatesAutoCodeAndSaves() {
        when(shortUrlRepository.existsByShortCode(anyString())).thenReturn(false);
        when(shortUrlRepository.save(any(ShortUrl.class))).thenAnswer(inv -> inv.getArgument(0));

        ShortUrl result = shortUrlService.createShortUrl("https://example.com", null, "user1");

        assertNotNull(result.getShortCode());
        assertEquals(7, result.getShortCode().length());
        assertFalse(result.isCustom());
        verify(shortUrlRepository).save(any(ShortUrl.class));
    }

    @Test
    void createShortUrl_withBlankAlias_usesAutoGeneration() {
        when(shortUrlRepository.existsByShortCode(anyString())).thenReturn(false);
        when(shortUrlRepository.save(any(ShortUrl.class))).thenAnswer(inv -> inv.getArgument(0));

        ShortUrl result = shortUrlService.createShortUrl("https://example.com", "   ", "user1");

        assertFalse(result.isCustom());
        verify(shortUrlRepository, never()).existsByShortCode("   ");
    }

    @Test
    void createShortUrl_withAliasTooShort_throwsInvalidAliasException() {
        ShortUrlService.InvalidAliasException ex = assertThrows(
                ShortUrlService.InvalidAliasException.class,
                () -> shortUrlService.createShortUrl("https://example.com", "ab", "user1"));
        assertTrue(ex.getMessage().contains("between"));
        verify(shortUrlRepository, never()).save(any());
    }

    @Test
    void createShortUrl_withAliasTooLong_throwsInvalidAliasException() {
        String longAlias = "a".repeat(33);
        assertThrows(ShortUrlService.InvalidAliasException.class,
                () -> shortUrlService.createShortUrl("https://example.com", longAlias, "user1"));
    }

    @Test
    void createShortUrl_withInvalidCharacters_throwsInvalidAliasException() {
        assertThrows(ShortUrlService.InvalidAliasException.class,
                () -> shortUrlService.createShortUrl("https://example.com", "bad alias!", "user1"));
    }

    @Test
    void createShortUrl_withReservedWord_throwsInvalidAliasException() {
        ShortUrlService.InvalidAliasException ex = assertThrows(
                ShortUrlService.InvalidAliasException.class,
                () -> shortUrlService.createShortUrl("https://example.com", "admin", "user1"));
        assertTrue(ex.getMessage().contains("reserved"));
    }

    @Test
    void createShortUrl_withExistingAlias_throwsAliasAlreadyExistsException() {
        when(shortUrlRepository.existsByShortCode("taken")).thenReturn(true);

        assertThrows(ShortUrlService.AliasAlreadyExistsException.class,
                () -> shortUrlService.createShortUrl("https://example.com", "taken", "user1"));
        verify(shortUrlRepository, never()).save(any());
    }

    @Test
    void createShortUrl_withRaceConditionOnSave_throwsAliasAlreadyExistsException() {
        when(shortUrlRepository.existsByShortCode("racey")).thenReturn(false);
        when(shortUrlRepository.save(any(ShortUrl.class)))
                .thenThrow(new DataIntegrityViolationException("duplicate"));

        assertThrows(ShortUrlService.AliasAlreadyExistsException.class,
                () -> shortUrlService.createShortUrl("https://example.com", "racey", "user1"));
    }

    @Test
    void createShortUrl_autoGenerated_retriesOnCollisionThenSucceeds() {
        when(shortUrlRepository.existsByShortCode(anyString()))
                .thenReturn(true, true, false);
        when(shortUrlRepository.save(any(ShortUrl.class))).thenAnswer(inv -> inv.getArgument(0));

        ShortUrl result = shortUrlService.createShortUrl("https://example.com", null, "user1");

        assertNotNull(result);
        verify(shortUrlRepository, times(3)).existsByShortCode(anyString());
        verify(shortUrlRepository, times(1)).save(any(ShortUrl.class));
    }

    @Test
    void createShortUrl_autoGenerated_exhaustsAttemptsAndThrows() {
        when(shortUrlRepository.existsByShortCode(anyString())).thenReturn(true);

        assertThrows(IllegalStateException.class,
                () -> shortUrlService.createShortUrl("https://example.com", null, "user1"));
        verify(shortUrlRepository, never()).save(any());
    }

    @Test
    void getByShortCode_whenFound_returnsShortUrl() {
        ShortUrl existing = new ShortUrl("abc1234", "https://example.com", false, "user1");
        when(shortUrlRepository.findByShortCode("abc1234")).thenReturn(Optional.of(existing));

        ShortUrl result = shortUrlService.getByShortCode("abc1234");

        assertEquals(existing, result);
    }

    @Test
    void getByShortCode_whenNotFound_throwsShortUrlNotFoundException() {
        when(shortUrlRepository.findByShortCode("missing")).thenReturn(Optional.empty());

        ShortUrlService.ShortUrlNotFoundException ex = assertThrows(
                ShortUrlService.ShortUrlNotFoundException.class,
                () -> shortUrlService.getByShortCode("missing"));
        assertTrue(ex.getMessage().contains("missing"));
    }
}
