package com.saigangili.shortener.service;

import com.saigangili.shortener.model.ShortUrl;
import com.saigangili.shortener.repository.ShortUrlRepository;
import org.springframework.dao.DataIntegrityViolationException;
import org.springframework.stereotype.Service;

import java.security.SecureRandom;
import java.util.Set;
import java.util.regex.Pattern;

@Service
public class ShortUrlService {

    // Note: redirect-path caching, analytics event storage, rate limiting,
    // and aggregation/reporting are out of scope for this pass and are
    // intentionally not implemented here, per current design decisions.

    private static final Pattern ALIAS_PATTERN = Pattern.compile("^[A-Za-z0-9_-]+$");
    private static final int ALIAS_MIN_LENGTH = 3;
    private static final int ALIAS_MAX_LENGTH = 32;
    private static final Set<String> RESERVED_WORDS = Set.of(
            "api", "admin", "login", "logout", "signup", "static", "assets",
            "health", "favicon.ico", "www", "urls", "redirect", "null", "undefined"
    );

    private static final String AUTO_CODE_ALPHABET =
            "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789";
    private static final int AUTO_CODE_LENGTH = 7;
    private static final int MAX_GENERATION_ATTEMPTS = 5;

    private final ShortUrlRepository shortUrlRepository;
    private final SecureRandom random = new SecureRandom();

    public ShortUrlService(ShortUrlRepository shortUrlRepository) {
        this.shortUrlRepository = shortUrlRepository;
    }

    public ShortUrl createShortUrl(String targetUrl, String customAlias, String createdBy) {
        if (customAlias != null && !customAlias.isBlank()) {
            return createWithCustomAlias(targetUrl, customAlias.trim(), createdBy);
        }
        return createWithAutoGeneratedCode(targetUrl, createdBy);
    }

    public ShortUrl getByShortCode(String shortCode) {
        return shortUrlRepository.findByShortCode(shortCode)
                .orElseThrow(() -> new ShortUrlNotFoundException("No URL found for code: " + shortCode));
    }

    private ShortUrl createWithCustomAlias(String targetUrl, String alias, String createdBy) {
        validateAlias(alias);

        if (shortUrlRepository.existsByShortCode(alias)) {
            throw new AliasAlreadyExistsException("The alias '" + alias + "' is already taken");
        }

        ShortUrl shortUrl = new ShortUrl(alias, targetUrl, true, createdBy);
        try {
            return shortUrlRepository.save(shortUrl);
        } catch (DataIntegrityViolationException e) {
            // Race condition: another request took the alias between check and insert
            throw new AliasAlreadyExistsException("The alias '" + alias + "' is already taken");
        }
    }

    private void validateAlias(String alias) {
        if (alias.length() < ALIAS_MIN_LENGTH || alias.length() > ALIAS_MAX_LENGTH) {
            throw new InvalidAliasException("Alias must be between " + ALIAS_MIN_LENGTH
                    + " and " + ALIAS_MAX_LENGTH + " characters long");
        }
        if (!ALIAS_PATTERN.matcher(alias).matches()) {
            throw new InvalidAliasException("Alias may only contain letters, digits, hyphens, and underscores");
        }
        if (RESERVED_WORDS.contains(alias.toLowerCase())) {
            throw new InvalidAliasException("Alias '" + alias + "' is a reserved word and cannot be used");
        }
    }

    private ShortUrl createWithAutoGeneratedCode(String targetUrl, String createdBy) {
        for (int attempt = 0; attempt < MAX_GENERATION_ATTEMPTS; attempt++) {
            String code = generateRandomCode();
            if (!shortUrlRepository.existsByShortCode(code)) {
                ShortUrl shortUrl = new ShortUrl(code, targetUrl, false, createdBy);
                try {
                    return shortUrlRepository.save(shortUrl);
                } catch (DataIntegrityViolationException e) {
                    // Collision on insert, retry with a new code
                }
            }
        }
        throw new IllegalStateException("Failed to generate a unique short code after "
                + MAX_GENERATION_ATTEMPTS + " attempts");
    }

    private String generateRandomCode() {
        StringBuilder sb = new StringBuilder(AUTO_CODE_LENGTH);
        for (int i = 0; i < AUTO_CODE_LENGTH; i++) {
            sb.append(AUTO_CODE_ALPHABET.charAt(random.nextInt(AUTO_CODE_ALPHABET.length())));
        }
        return sb.toString();
    }

    public static class InvalidAliasException extends RuntimeException {
        public InvalidAliasException(String message) {
            super(message);
        }
    }

    public static class AliasAlreadyExistsException extends RuntimeException {
        public AliasAlreadyExistsException(String message) {
            super(message);
        }
    }

    public static class ShortUrlNotFoundException extends RuntimeException {
        public ShortUrlNotFoundException(String message) {
            super(message);
        }
    }
}
